### ISSUE TITLE
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: EntityManagerFactory must not be null

### ISSUE THREAD

**Issue by tuxedo** [chuangchidong/dquery-spring-boot-starter#1]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: EntityManagerFactory must not be null

**Comment by chuangchidong** [comment]
怎么出现的

**Comment by tuxedo** [comment]
SpringBoot 2.1+

**Comment by tuxedo** [comment]
private SessionFactory sessionFactory;

	@Autowired
	private EntityManagerFactory entityManagerFactory;

	@PostConstruct
	public void init() {
		logger.info("init DQueryAutoConfiguration start");
		sessionFactory = entityManagerFactory.unwrap(SessionFactory.class);
		this.pointcut = new AnnotationMatchingPointcut(null, DQuery.class);
		this.advice = new DQueryMethodInterceptor(sessionFactory);
		logger.info("init DQueryAutoConfiguration end");
	}

**Comment by tuxedo** [comment]
存在问题
sessionFactory 配置版本较旧
springboot的版本需要换成2.0以上
都已经解决

**Comment by tuxedo** [comment]
using:
//<parent>
       // <groupId>org.springframework.boot</groupId>
        //<artifactId>spring-boot-starter-parent</artifactId>
        //<version>2.1.0.RELEASE</version>
    //</parent>

**Comment by chuangchidong** [comment]
EntityManagerFactory需要一个实现类吧

**Comment by tuxedo** [comment]
SpringBoot 2.X会自动配置注入
